language: go

go:
  - master
sudo: required
branches:
  only:
    - master
    - tag
services:
  - docker
script:
  - echo ${dockerpwd}|docker login -u ${dockeruser} -password-stdin
  - make publish

after_success:
  - make compose

