language: go
go:
- master
sudo: required
branches:
  only:
  - master
  - tag
services:
- docker
script:
- docker login -u $dockeruser -p $dockerpwd
- docker build . -t t-go-opentrace:latest
- docker push asppj/t-go-opentrace:latest
after_success:
- make compose
before_install:
- openssl aes-256-cbc -K $encrypted_be7dabd7bd4d_key -iv $encrypted_be7dabd7bd4d_iv
  -in deploy_rsa.enc -out deploy_rsa -d
