language: go

go:
  - master
sudo: required
branches:
  only:
    - master
    - tag
services:
  - docker
script:
  - make build
  - docker login  -u ${dockeruser} -p ${dockerpwd}

after_success:
  - make compose
  - make publish
