language: go

go:
  - master
sudo: required
branches:
  only:
    - master
    - tag
services:
  - docker
script:
  - make compose
#  - docker login  -u ${dockeruser} -p ${dockerpwd}

#after_success:
#  - make publish
