language: go

go:
  - master
sudo: required
branches:
  only:
    - master
    - tag
services:
  - docker
script:
  - docker login -u $dockeruser -p $dockerpwd
  - docker build . -t t-go-opentrace:latest
  - docker push asppj/t-go-opentrace:latest

after_success:
  - make compose

