language: go
go:
  - master
sudo: required
branches:
  only:
    - master
    - tag
addons:
  hosts:
    - asppj.top
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_be7dabd7bd4d_key -iv $encrypted_be7dabd7bd4d_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
install:
  - echo $TARGET_PATH
  - echo $dockeruser
  - docker build . -t t-go-opentrace:latest
  - rsync -az --delete ./dist/* $USER_NAME@$HOST:TARGET_PATH
script:
  - docker login -u $dockeruser -p $dockerpwd
  - docker push asppj/t-go-opentrace:latest
after_success:
  - make compose



