version: "3"
services:
  app:
    build:
      context: tools/docker-compose/app
      dockerfile: tools/docker-compose/app/Dockerfile
    container_name: app_github
    privileged: true
    extra_hosts:
      - "github.global.ssl.fastly.net:151.101.185.194"
      - "github.com:192.30.253.112"
    volumes:
      - .:/app
    ports:
      - 5000
      - 50000
    environment:
      httPort: 5000
      rpcPort: 50000
      MgoUser: kegel-admin
      MgoPwd: lsp123123
      GOPROXY: "https://goproxy.cn,direct"
    command:
      go run main.go