name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: go build -v .

      - name: Deploy to Staging server
        uses: AEnterprise/rsync-deploy@v1.0
          env:
            DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-e -c -r --delete"
            SERVER_PORT: ${{ secrets.REMOTE_PORT }}
            FOLDER: "./"
            SERVER_IP: ${{ secrets.REMOTE_HOST }}
            USERNAME: ${{ secrets.REMOTE_USER }}
            SERVER_DESTINATION: ${{ secrets.REMOTE_TARGET }}